language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: DucklingHTTPExtractor
  url: http://localhost:8000
  dimensions:
  - phone-number
  - email
  locale: de_DE
  timezone: Europe/Berlin
  timeout: 3
- name: SpacyNLP
  model: en_core_web_md
  case_sensitive: false
- name: SpacyEntityExtractor
  dimensions:
  - PERSON
- name: FallbackClassifier
  thershold: 0.65
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
